services:
  - type: web
    name: mafia-syndicate-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: REGISTRATION_TIME
        value: "60"
      - key: NIGHT_TIME
        value: "60"
      - key: DAY_VOTE_TIME
        value: "90"
